//
//  Data.swift
//  List
//
//  Created by Yazid Al Ghazali on 01/12/20.
//

import Foundation

let data = [
    Film(name: "Teman Tapi Menikah 2", desc: "Belum puas menikmati momen sebagai pasangan baru, Ayu tiba-tiba hamil. Kepribadiannya berubah total. Dari yang tadinya semangat nemenin Ditto ke mana-mana, ia jadi mager dan parahnya, super sensitif! Ditto pun harus menahan diri dan pura-pura tidak cemburu dengan perhatian yang Ayu berikan ke si janin. Pertengkaran yang sering terjadi membuat Ayu dan Ditto harus memilih mana yang mau dipertahankan; pernikahan mereka atau si bayi?", rilisDate: "27 Februari 2020", sutradara: "Rako Prijanto", image: "ttm", duration: "1 Jam 40 Menit"),
    Film(name: "Akhir Kisah Cinta Si Doel", desc: "Kepulangan SARAH bersama DUL ke Jakarta, disambut bahagia oleh keluarga DOEL. Namun hal tersebut juga membuat ZAENAB, SARAH, dan DOEL dihadapkan pada pilihan besar. ZAENAB yang positif hamil dan masih trauma pernah kehilangan buah hati di masa lalu, kini harus memilih antara tetap berada di sisi DOEL, atau merelakannya demi menyatukan kembali sebuah keluarga.", rilisDate: "23 Januari 2020", sutradara: "Rano Karno", image: "kisahdoel", duration: "1 Jam 33 Menit"),
    Film(name: "Guru-guru Gokil", desc: "Guru-guru Gokil adalah film Indonesia tahun 2020 yang disutradarai Sammaria Simanjuntak dan dibintangi Gading Marten, Dian Sastrowardoyo, Faradina Mufti, Boris Bokir, dan Kevin Ardilova. Film ini menjadi debut Dian sebagai produser. Film terbaru produksi BASE Entertainment, akan tayang secara eksklusif di Netflix.", rilisDate: "17 Agustus 2020", sutradara: "Sammaria Simanjuntak", image: "gurugokil", duration: "1 Jam 44 Menit"),
    Film(name: "Bucin", desc: "Merasa bahwa mereka bucin, Jovial (29) mendaftarkan adiknya, Andovi (25), dan teman- temannya , Tommy (24) dan Chandra (26), untuk mengikuti kursus anti-bucin. Tujuan kursus ini adalah untuk mengajarkan cara memiliki hubungan yang sehat dan tidak hanya menguntungkan satu pihak. Kursus ini dibuat oleh Vania (29), seorang lulusan S2 psikologi dengan spesialisasi cinta. Ternyata metode yang digunakan oleh Vania tidak konvensional dan lumayan ekstrim, dia menggunakan konsep ESCAPE ROOM untuk menjelaskan konsep cinta. Sering kali mereka ingin berhenti karena tidak sanggup.", rilisDate: "26 Maret 2020", sutradara: "Chandra Liow", image: "bucin", duration: "1 Jam 37 Menit"),
    Film(name: "Toko Barang Mantan", desc: "Toko Barang Mantan adalah toko jual-beli barang-barang mantan bagi orang-orang yang ingin move-on dari mantannya. Sebagai pencetus ide, pendiri dan pemiliknya, Tristan rela meninggalkan kuliah hukumnya demi bisa fokus mengembangkan toko ini bersama sahabatnya, Amel dan Rio. Berbagai macam kisah-kisah sedih, lucu dan absurd tentang barang-barang tersebut menjadi makanan mereka sehari-hari.", rilisDate: "18 Februari", sutradara: "Viva Westi", image: "tbm", duration: "1 Jam 38 Menit"),
    Film(name: "Milea: Suara dari Dilan", desc: "Tidak ada kisah yang lebih Indah dari kisah cinta di SMA.Sama halnya dengan kisah cinta Dilan dan Milea.Dari yang awalnya benci hingga saling mencintai. Dari yang awalnya manis hingga menjadi rumit.Menjelang reuni akbar,Dilan memutuskan untuk menceritakan kembali masa masa itu.", rilisDate: "13 Februari 2020", sutradara: "Pidi Baiq, Fajar Bustomi", image: "milea", duration: "1 Jam 42 Menit"),
    Film(name: "Temen Kondangan", desc: "Ketakutan terbesar Putri (Prisia Nasution) akhirnya datang ketika menerima undangan resepsi pernikahan mantan pacar terindahnya, Dheni (Samuel Rizal). Untuk membuktikan kalau dirinya sudah move-on, Putri ditantang oleh sahabat-sahabatnya untuk hadir ke pesta tersebut, dengan syarat tidak datang sendirian.", rilisDate: "30 Januari 2020", sutradara: "Lip Sariful Hanan", image: "temenKondangan", duration: "1 Jam 26 Menit")
]
